# Changes here will be overwritten by Copier
_commit: v0.3
_src_path: gh:LSSTDESC/RAIL-project-template
author_email: samuel.j.schmidt@gmail.com
author_name: LSST Dark Energy Science Collaboration (DESC) Photo-z WG
create_example_module: false
package_name: bpz
project_name: pz-rail-bpz
